/**
 * Types for the extracted scenario datasets.
 *
 * These mirror packages/data/schema/*.schema.json. The JSON is generated by
 * tools/extract/extract.py from the game's master.mdb -- never hand-edited.
 */

// ---------------------------------------------------------------------------
// Shared vocabulary
// ---------------------------------------------------------------------------

/** The five trainee stats. */
export const STATS = ["speed", "stamina", "power", "guts", "wit"] as const;
export type Stat = (typeof STATS)[number];

/** Grand Concert's five performance token currencies. */
export const TOKENS = ["dance", "passion", "vocal", "visual", "mental"] as const;
export type Token = (typeof TOKENS)[number];

/** A training facility. One per stat. */
export type Facility = Stat;

export type StatVector = Record<Stat, number>;
export type TokenVector = Record<Token, number>;

/**
 * An effect granted by a technique or song.
 *
 * `text` is the game's own English description -- authoritative for display.
 * `raw` is the undecoded opcode tuple from master.mdb, kept so the engine can
 * learn to interpret effects incrementally without re-extracting. Do not invent
 * semantics for `raw`; decode it against observed behaviour and add a test.
 */
export interface Effect {
  text: string | null;
  raw: number[];
}

// ---------------------------------------------------------------------------
// Grand Concert dataset
// ---------------------------------------------------------------------------

export type TechniqueKind =
  | "technique_stat"
  | "technique_hint"
  | "technique_energy";

export interface Technique {
  id: number;
  name: string | null;
  kind: TechniqueKind;
  cost: TokenVector;
  effect: Effect;
}

export interface Song {
  id: number;
  name: string | null;
  cost: TokenVector;
  /** Applies immediately on purchase. */
  mastery_bonus: Effect;
  /**
   * Applies from the NEXT concert until the end of the career -- not on
   * purchase. That timing is the whole reason song ordering matters: a bonus
   * bought before Classic June multiplies every remaining training, the same
   * bonus bought in Senior November multiplies almost none.
   *
   * The game ships the wording (text_data category 208, keyed by
   * `single_mode_live_song_list.id`), so this is READ, not decoded. Before
   * 2026-09-06 only the opcode below was extracted and nothing applied it.
   */
  concert_bonus: Effect;
  /**
   * The raw opcode behind `concert_bonus`. Kept only so a future extraction can
   * check the wording still matches the type it claims to describe. Nothing
   * derives behaviour from it.
   */
  concert_bonus_type: number | null;
  concert_bonus_value: number | null;
  live_id: number | null;
}

export interface Concert {
  index: number;
  /** Career turn on which this concert happens. */
  turn: number;
  songs_for_great_success: number;
  is_grand_concert: boolean;
}

export interface GrandConcertConstants {
  tokens: Token[];
  /** Which token each facility pays out. */
  facilityTokens: Record<Facility, { primary: Token; secondary: Token }>;
  /** P(primary) / P(secondary) / P(anything else) on a training payout. */
  tokenRollWeights: { primary: number; secondary: number; other: number };
  statCaps: StatVector;
  careerTurns: number;
}

export interface DatasetSource {
  file: string;
  sha256: string;
  mtime?: string;
  extractedAt: string;
}

export interface GrandConcertDataset {
  schemaVersion: 1;
  scenario: "grand-concert";
  source: DatasetSource;
  constants: GrandConcertConstants;
  concerts: Concert[];
  techniques: Technique[];
  songs: Song[];
}

// ---------------------------------------------------------------------------
// Skill index (scenario-independent)
// ---------------------------------------------------------------------------

export interface SkillEntry {
  id: number;
  name: string;
  description: string | null;
  rarity: number;
  /** SP price in career mode. null means the skill cannot be bought. */
  spCost: number | null;
  purchasableInCareer: boolean;
  raw: { disableSingleMode: number };
}

export interface SkillIndex {
  schemaVersion: 1;
  source: { sha256: string };
  skills: SkillEntry[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export const ZERO_TOKENS: TokenVector = {
  dance: 0,
  passion: 0,
  vocal: 0,
  visual: 0,
  mental: 0,
};

export const ZERO_STATS: StatVector = {
  speed: 0,
  stamina: 0,
  power: 0,
  guts: 0,
  wit: 0,
};

export function tokenTotal(v: TokenVector): number {
  return TOKENS.reduce((sum, t) => sum + v[t], 0);
}

/** True if `have` covers every token in `cost`. */
export function canAfford(have: TokenVector, cost: TokenVector): boolean {
  return TOKENS.every((t) => have[t] >= cost[t]);
}

export function subtractTokens(a: TokenVector, b: TokenVector): TokenVector {
  return {
    dance: a.dance - b.dance,
    passion: a.passion - b.passion,
    vocal: a.vocal - b.vocal,
    visual: a.visual - b.visual,
    mental: a.mental - b.mental,
  };
}
